package event

// SyncState ...
type SyncState string

const (
	//LOCKED ...
	LOCKED SyncState = "LOCKED"

	//UNLOCKED ...
	UNLOCKED SyncState = "UNLOCKED"

	//HOLDOVER ...
	HOLDOVER SyncState = "HOLDOVER"

	//FREERUN ...
	FREERUN SyncState = "FREERUN"

	//SYNCHRONIZED ...
	SYNCHRONIZED SyncState = "SYNCHRONIZED"

	//ACQUIRING_SYNC ...
	ACQUIRING_SYNC SyncState = "ACQUIRING-SYNC"

	// ANTENNA_DISCONNECTED ...
	ANTENNA_DISCONNECTED SyncState = "ANTENNA-DISCONNECTED"

	//BOOTING ...
	BOOTING SyncState = "BOOTING"

	// ANTENNA_SHORT_CIRCUIT ...
	ANTENNA_SHORT_CIRCUIT SyncState = "ANTENNA-SHORT-CIRCUIT"
)

